### PR TITLE
PSG-4798

### PR DESCRIPTION
**Pull request by SinaSeylani**
# Pull Request Template

## What's New?

generated code is updated

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have manually tested my code thoroughly
- [x] I have added/updated inline documentation for public facing interfaces if relevant
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing integration and unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Jira Ticket

Please add the Jira ticket number and link.

- [ ] Jira Ticket: [PSG-4798](https://passage-identity.atlassian.net/browse/PSG-4798)

[PSG-4798]: https://passage-identity.atlassian.net/browse/PSG-4798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rickycpadilla — COMMENTED** [review]
I see some changes in the generated code that I assume would impact non-openapi code, but I don't see any updates except in the generated code. Are you sure we don't need to change anything else?

Examples:
* `UserMetaDataResponse.userMetadata` is now optional
* `CredentialAssertionChallenge.handshake` and `AuthenticateWebAuthnStartWithTransactionResponse.handshake` class changed
* Create user response changed

**Comment by rickycpadilla** [comment]
Regarding the SonarCloud quality gate failure - you can exclude the generated code from analysis.

**Comment by SinaSeylani** [comment]
> I see some changes in the generated code that I assume would impact non-openapi code, but I don't see any updates except in the generated code. Are you sure we don't need to change anything else?
> 
> Examples:
> 
> * `UserMetaDataResponse.userMetadata` is now optional
> * `CredentialAssertionChallenge.handshake` and `AuthenticateWebAuthnStartWithTransactionResponse.handshake` class changed
> * Create user response changed

I don't think these changes will affect the return type (like AuthResult). I've tested it a few times manually, and everything works fine for login and sign-up with passkey, OTP, etc. Is there any area you think might be impacted by this?

**Review by rickycpadilla — APPROVED** [review]
Nice work!

**Pull request merged**
